# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Uplift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Uplift
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'SwiftDate'
  pod 'GrowingTextView'
  pod 'IQKeyboardManagerSwift'
  pod 'RealmSwift'
end
