# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'LextTalk' do
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'Google-Mobile-Ads-SDK', '~> 7.11.0'
pod 'AdMobMediationAdapterIAd'
pod 'Appirater'
pod 'Flurry-iOS-SDK/FlurrySDK'
#pod 'Flurry-iOS-SDK/FlurryAds'
pod 'Fabric'
pod 'Google/Analytics'
pod 'Crashlytics'
pod 'IQLocationManager', :git => 'http://gitlab.inqbarna.com/internal/iq-location-manager-ios.git'
pod 'LAWalkthrough', '~> 1.0'
pod 'SCLAlertView-Objective-C', '~> 1.0'
end

target 'LextTalkCatalan' do

end

