# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UPLIFT' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UPLIFT
	pod ‘Firebase’
	pod ‘Firebase/Database’
	pod ‘Firebase/Storage’
	#pod ‘Firebase/Storage’
	#pod 'Firebase/Core'
	pod ‘FBSDKCoreKit’
	pod ‘FBSDKLoginKit’
	pod ‘FBSDKShareKit’
end
